# Generated by Django 4.0.4 on 2022-06-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinopoisk_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cinemas',
            field=models.ManyToManyField(blank=True, related_name='avaliable_movies', to='kinopoisk_app.cinema', verbose_name='Кинотеатры'),
        ),
    ]
