# Generated by Django 4.0.4 on 2022-05-27 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kinopoisk_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='movie',
            name='actor_squad',
            field=models.ManyToManyField(related_name='movies', to='kinopoisk_app.actor', verbose_name='Актеры'),
        ),
        migrations.AddField(
            model_name='movie',
            name='film_director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinopoisk_app.director', verbose_name='Режиссер'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinopoisk_app.genre'),
        ),
        migrations.AddField(
            model_name='director',
            name='filmography',
            field=models.ManyToManyField(blank=True, null=True, related_name='director', to='kinopoisk_app.movie', verbose_name='Фильмы'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='avaliable_movies',
            field=models.ManyToManyField(blank=True, null=True, to='kinopoisk_app.movie', verbose_name='Доступные фильмы'),
        ),
        migrations.AddField(
            model_name='actor',
            name='filmography',
            field=models.ManyToManyField(blank=True, null=True, related_name='actors', to='kinopoisk_app.movie', verbose_name='Фильмы'),
        ),
    ]
