# Generated by Django 4.0.4 on 2022-05-24 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kinopoisk_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='filmography',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kinopoisk_app.movie'),
        ),
    ]
