# Generated by Django 4.0.4 on 2022-06-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinopoisk_app', '0002_alter_customuser_options_alter_movie_film_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='filmography',
        ),
        migrations.RemoveField(
            model_name='cinema',
            name='avaliable_movies',
        ),
        migrations.AddField(
            model_name='movie',
            name='cinemas',
            field=models.ManyToManyField(related_name='avaliable_movies', to='kinopoisk_app.cinema', verbose_name='Кинотеатры'),
        ),
    ]
