# Generated by Django 4.0.4 on 2022-06-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinopoisk_app', '0003_remove_director_filmography'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='city',
            field=models.CharField(choices=[('Kyiv', 'Kyiv'), ('Vinnitsa', 'Vinnitsa'), ('Uman', 'Uman'), ('Zaporozhje', 'Zaporozhje'), ('Kharkov', 'Kharkov'), ('Lvov', 'Lvov'), ('Poltava', 'Poltava'), ('Zhitomir', 'Zhitomir'), ('Dnepr', 'Dnepr'), ('Lutsk', 'Lutsk'), ('Chernovrtsi', 'Chernovrtsi'), ('Uzhgorod', 'Uzhgorod'), ('Kherson', 'Kherson')], default='Not specified', max_length=100, verbose_name='Город'),
        ),
    ]
