# Generated by Django 4.0.4 on 2022-06-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinopoisk_app', '0003_remove_actor_filmography_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='filmography',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='favorite_genres',
            field=models.ManyToManyField(blank=True, to='kinopoisk_app.genre', verbose_name='Любимые жанры'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='favorite_movies',
            field=models.ManyToManyField(blank=True, to='kinopoisk_app.movie', verbose_name='Избранные фильмы'),
        ),
    ]
