# Generated by Django 4.0.4 on 2022-06-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinopoisk_app', '0004_cinema_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='name',
            field=models.CharField(choices=[('Multiplex', 'Multiplex'), ('Butterfly', 'Butterfly'), ('Planeta kino', 'Planeta kino'), ('Oskar', 'Oskar'), ('Sputnik', 'Sputnik'), ('Liniya kino', 'Liniya kino'), ("Kievskaya Rus'", "Kievskaya Rus'")], default='Not specified', max_length=100, verbose_name='Название'),
        ),
    ]
